// This file is auto-generated by `scripts/update.ts`.

/**
 * Set of UTC dates (YYYY-MM-DD) on which a positive leap second was inserted.
 *
 * Source: https://data.iana.org/time-zones/data/leap-seconds.list
 *
 * Last verified: 2026-05-15
 *
 * Note: The source contains as a first entry a timestamp that is not part of
 * this list here. The first entry (dtai == 10) doesn't represent a leap second
 * being inserted. It's just the baseline: when the leap second system started
 * on 1972-01-01, TAI was already 10 seconds ahead of UTC. That offset was set
 * by convention, not by a leap second event.
 *
 * @type {Set<string>}
 */
export const leapSeconds = new Set([
  '1972-06-30',
  '1972-12-31',
  '1973-12-31',
  '1974-12-31',
  '1975-12-31',
  '1976-12-31',
  '1977-12-31',
  '1978-12-31',
  '1979-12-31',
  '1981-06-30',
  '1982-06-30',
  '1983-06-30',
  '1985-06-30',
  '1987-12-31',
  '1989-12-31',
  '1990-12-31',
  '1992-06-30',
  '1993-06-30',
  '1994-06-30',
  '1995-12-31',
  '1997-06-30',
  '1998-12-31',
  '2005-12-31',
  '2008-12-31',
  '2012-06-30',
  '2015-06-30',
  '2016-12-31',
])
