import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'

const SOURCE_URL = 'https://data.iana.org/time-zones/data/leap-seconds.list'

/** Seconds between NTP epoch (1900-01-01) and Unix epoch (1970-01-01). */
const NTP_UNIX_DELTA = 2208988800n

/**
 * Converts an NTP timestamp to a UTC date string (YYYY-MM-DD).
 *
 * The NTP timestamp marks the moment the new TAI-UTC offset takes effect
 * (i.e. the first second *after* the leap second). Subtracting 1 second
 * gives the date on which the leap second was actually inserted (always
 * June 30 or December 31).
 */
function ntpToDate(ntp: bigint): string {
  const unixMs = Number(ntp - NTP_UNIX_DELTA - 1n) * 1000
  return new Date(unixMs).toISOString().slice(0, 10)
}

const response = await fetch(SOURCE_URL)
if (!response.ok) {
  throw new Error(
    `Failed to fetch ${SOURCE_URL}: ${response.status} ${response.statusText}`,
  )
}
const text = await response.text()

const dates: string[] = text
  .split('\n')
  .filter((line) => /^\d+\s+\d+/.test(line))
  .map((line) => {
    const [ntpStr, dtaiStr] = line.trim().split(/\s+/)
    return { ntp: BigInt(ntpStr!), dtai: Number(dtaiStr!) }
  })
  // dtai == 10 is the initial TAI-UTC offset from 1972-01-01, not a leap second insertion
  .filter(({ dtai }) => dtai > 10)
  .map(({ ntp }) => ntpToDate(ntp))
  .sort()

const today = new Date().toISOString().slice(0, 10)

const content = `\
// This file is auto-generated by \`scripts/update.ts\`.

/**
 * Set of UTC dates (YYYY-MM-DD) on which a positive leap second was inserted.
 *
 * Source: ${SOURCE_URL}
 *
 * Last verified: ${today}
 *
 * Note: The source contains as a first entry a timestamp that is not part of
 * this list here. The first entry (dtai == 10) doesn't represent a leap second
 * being inserted. It's just the baseline: when the leap second system started
 * on 1972-01-01, TAI was already 10 seconds ahead of UTC. That offset was set
 * by convention, not by a leap second event.
 *
 * @type {Set<string>}
 */
export const leapSeconds = new Set([
${dates.map((d) => `  '${d}',`).join('\n')}
]);
`

const outPath = resolve(
  fileURLToPath(import.meta.url),
  '../../lib/leapSeconds.js',
)

const formatted = await format(content, {
  ...(await resolveConfig(outPath)),
  filepath: outPath,
})

await writeFile(outPath, formatted, 'utf-8')

console.log(
  `Updated lib/leapSeconds.js with ${dates.length} leap seconds (last: ${dates.at(-1)}).`,
)
